#+TITLE: About Me
#+AUTHOR: Philip Dumaresq
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="assets/org.css" />
#+OPTIONS: toc:nil

#+BEGIN_CENTER
[[file:index.org][Home]] | [[file:about.org][About]] | [[file:contact.org][Contact]]
#+END_CENTER

* Hi, my name is Philip! 

I'm a passionate developer living in Montreal Canada, currently taking some time off school due to
covid. Normally I'm a student at Concordia University, but right now I'm focusing on building
open-source projects and looking for full-time work.

** My Background
Before starting in university, I completed a 3-year technical degree in Computer Science from 
Heritage college in Gatineau, Quebec. This program was invaluable to me, and shaped my view of 
programming. I spent two summers before university working as a full-stack developer for 
TechInsights, and 2 semester in college working as a TA. 

** Personal Interests 
Outside of Computer Science or programming, I love going rock climbing and being outdoors. I love 
camping and hiking in the summer, and during the winter I enjoy going out skiing and skating. 
Being from Ottawa, I've been spoiled all my life by the Rideau Canal, 
