#+TITLE: Home
#+AUTHOR: Philip Dumaresq
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="assets/org.css" />
#+OPTIONS: toc:nil

#+BEGIN_CENTER
[[file:index.org][Home]] | [[file:about.org][About]] | [[file:contact.org][Contact]]
#+END_CENTER

* Projects
- [[https://github.com/nixin72/dotfiles][dotfiles]]: My constantly tinkered-with dotfiles for linux
- [[https://github.com/nixin72/from-template][from-template]]: A Racket tool for using templates
- [[https://github.com/nixin72/block-nav.el][block-nav.el]]: An Emacs package for navigation
- [[https://github.com/nixin72/window-bind-buffer.el][window-bind-buffer.el]]: An Emacs package for modern buffer/window management

* [[file:blog/index.org][Blog]]
 
** [[file:blog/joy-of-racket.org][The Joy of learning Racket]]
#+BEGIN_small 
December 14th, 2019 | 8 minute read
#+END_small

Recently I started learning Racket and it's the most fun I've had learning a new language in a long
time. In this post I'll talk about what was great about Racket and how you can get started.
** [[file:blog/lisp-uninitiated.org][Lisp for the uninitiated]]
#+BEGIN_small 
November 10th, 2019 | 15 minute read
#+END_small

For many people, Lisp is a mystical programming language they hear of here and there, and hear of
it's great power. Well, Lisp is amazing, but I'm gonna demystify it a bit for you.

* COMMENT Talks
** [[http://github.com/nixin72/talks/tree/master/meta-programming][Meta Programming and Macros]] 
#+BEGIN_small
October 18th 2020
#+END_small

What is meta-programming? What are macros? Why use them? This talk gives and introduction to macros
and meta-programming in Common Lisp. We define a small DSL in Lisp for writing SQL queries.

* [[file:questions/index.org][Questions]]
This section is all related to questions that have been asked by students, with the questions and
answers preserved here for use by future students.

** COMMENT Java
This section is for all questions relating to Java, in particular the ~stream~ API.

** Lisp
This section is for all questions relating to Lisp, Scheme, Clojure, etc
- [[file:questions/lisp-setting-variables.org][How to declare and set variables in Lisp]]
- [[file:questions/lisp-quote-vs-'.org][The difference between ~quote~ and ~'~]]
- [[file:questions/lisp-let-scoping.org][Variable scoping and ~let~ bindings]]

** COMMENT Prolog
This section is for all questions relating to Prolog

** COMMENT C
This section is for all questions relating to Lisp, Scheme, Clojure, etc

** COMMENT Ruby
This section is for all questions relating to Lisp, Scheme, Clojure, etc
