#+TITLE: Clojure Design
#+SETUPFILE: ../templates/html.org
#+INCLUDE: header.org

I have a tendency to "go-off" sometimes when asked questions, and when tutoring students in Common
Lisp, it can be tough sometimes to avoid letting my negative opinions about Common Lisp or positive
opinions about Clojure through. I was asked why I liked Clojure so much the other day though, so I
figured I'd give a detailed answer about that.

**** Immutability
First of all, everything is immutable by default. This can be a bit weird to overcome when you first
start using it, but reassignment in Clojure is rare. This makes testing code super easy because
you’re always dealing with pure functions and the headaches that come with mutation aren’t something
you need to think about. But making changes to data is still incredibly easy:
#+BEGIN_SRC clojure
(let [hashmap {:a 1 :b 2 :c 3}]
  (println hashmap)              ;; {:a 1, :b 2, :c 3}
  (println (assoc hashmap :a 2)) ;; {:a 2, :b 2, :c 3}
  (println hashmap))             ;; {:a 1, :b 2, :c 3}
#+END_SRC
I can use a wide variety of functions to produce new data structures that are modified versions of
the old ones, but in Clojure these operations never change the original data structure. Normally
this would require a lot of values, which is very inefficient, so Clojure utilizes a technique call
*[[https://hypirion.com/musings/understanding-persistent-vector-pt-1][structural sharing]]* to reduce the memory footprint of doing this.

**** Thread-safety
In the instances where mutation is necessary, Clojure provides thread-safe mechanisms for updating
values to keep them synchronized across threads. This makes Clojure very good for building largely
concurrent applications. Here's a simple example of using an ~atom~ to synchronize a value across two
threads.
#+BEGIN_SRC clojure
(let [val (atom 0)
      fut (future
            (doseq [x (range 10)]
              (println @val)
              (swap! val inc)))]
  (loop []
    (when-not (future-done? fut)
      (println @val)
      (recur))))
#+END_SRC
This will print 1-10, perhaps in a weird order, but with the value of ~val~ being kept in-sync between
the main thread and the future thread.

**** Data structures
Clojure also features really good first-class support for a lot of data structures - lists, vectors,
hashmaps, sets, stacks and queues. So the data structure you need is always right there. All of
these data structures can be interacted with through the sequence interface, a huge collection of
100+ functions that perform tons of different operations on sequences. Practically any operation you
want - reverse order, sort, sort-by, group-by, frequencies of elements, mappings, reductions,
slices, zipping, tree-walking, etc. And any type of transformation that isn’t there is usually
really easy to express as a composition of other operations.
#+BEGIN_SRC clojure
[:this :is :a :vector]
(:this :is :a :list)
{:this :is :a :hashmap}
#{:this :is :a :set}
#+END_SRC

**** Threading
The language also allows transformations to always be easily expressed as a pipeline of data. In
Java you can only ~.a().b().c()~ so long as the APIs were designed to work that way, but in Clojure
you can pipe the output of any function as the input to any other, which makes data transformations
very clear to express. The functions are all also just designed to work incredibly well together in
a very predictable way. The expected result is almost always what you get when messing around with
things.
#+BEGIN_SRC clojure
(map (fn [x] (do-c x))
     (filter (fn [x] (do-b x))
             (reduce (fn [a x] (do-a a x))
                     []
                     some-vector)))
;; turns into
(->> some-vector
     (reduce (fn [a x] (do-a a x)) [])
     (filter (fn [x] (do-b x)))
     (map (fn [x] (do-c x))))
#+END_SRC

**** Scalability
Clojure also has an excellent solution to scalability. There’s this well known problem called the
/expression problem/ that OOP and Functional languages need to deal with. OOP languages struggle to
extend an existing type to have other functionalities and functional languages struggle to extend an
existing functionality to work with more types. Clojure provides a solution to this problem in both
directions by allowing you to create what it calls multi-methods and protocols, that can extend a
type or functionality.

An example would be a little long to provide here, but check out [[https://eli.thegreenplace.net/2016/the-expression-problem-and-its-solutions/][Eli Bendersky's article that
explains this well.]]

**** Ecosystem
Clojure is also a hosted language, meaning it runs on top of other platforms and ecosystems. It's
official implementations support compiling to JVM, JavaScript or dotnet, which means Clojure has
access to millions of libraries and has a massive ecosystem. There’s always going to be a library to
do what you want pretty much, and Clojure has absolutely seamless interop with whatever host
language you’re targeting. Most of the time however, the Java libraries aren't exactly idiomatic
Clojure, so Clojure has it's own package ecosystem too, [[https://clojars.org/][Clojars]], that has tens of thousands of
Clojure libraries.

**** Macros
By virtue of being a lisp, Clojure also has macros, which are basically functions that run at
compile time and transform your code. This lets you build your own syntax in Clojure whenever you
find something that isn’t very nice to express normally, or when you just want to abstract away some
details you don’t want people to have to worry about. Macros are an awesome abstraction tool that
not many languages have.

#+BEGIN_SRC clojure
(defmacro when [cond & body]
  `(if ~cond (do ~@body) nil))

(when (= a b)
  (println a)
  (println b)
  (println (+ a b)))
#+END_SRC

Some do however, such as Rust and Nim, but macros in those languages are complex because you need to
deal with tokens in an abstract syntax tree and producing new valid code can be a complex process.
In Clojure however, since the various data structurs share the same syntax as Clojure itself,
writing macros is just a matter of using the same good library of 100+ sequence functions. No need
to learn a whole complex macro system.

**** Ergonomics
Clojure has also just got so many other small niceties. Commenting out a single expression, even if
it’s several lines long, with a single comment symbol. Short-hand syntax for lambda functions.
Syntax support for regular expressions. Syntax for all the core data structures. Short and sane
function names. A testing library built in. And so many other things that are just really nice to
have in a language. Things that don't make or break it, but when you're using the language you say
"damn, I wish <other-lang> had this."

**** Simple
After all of this, Clojure is, at its core, a super simple language. I think most people could learn
enough Clojure to be productive in a weekend. The biggest hurdle is the syntax, which there's
countless tools out there to help make it easier to work with. Basically all you have to learn is
how to make functions, declare variables, conditionals, and then slowly learn functions in the
standard library - 90% of which is super easily accessible through a [[https://clojure.org/api/cheatsheet][cheatsheet]] on the Clojure
website. And with sane function names, you don’t even have to look at the docs for that function
most of the time cause it just does what you expect.

**** Conclusion
Clojure is an incredibly well designed language, and I've never felt quite so comfortable using
anything else before. I have no real complaints about Clojure in the 2 years since I first started
learning it, and I have no intention of moving on from it any time soon. I would highly recommend
learning Clojure to anyone who wants a language that's designed around the very real complexities of
modern software development and offers a solution to cut through a lot of that complexity to make
simpler, understandable, and scalable solutions to real-world problems.
