#+TITLE: The Joy of Learning Racket
#+AUTHOR: Philip Dumaresq
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../assets/org.css" />

* The Joy of Learning Racket
I recently took up learning Racket, and I've really been loving it. This is just a short mind 
dump/rant of what I've been loving about Racket so far.

First of all, it's a lisp, as a language nerd, I love me some Lisp, so there's some points to it 
right there. Second of all, it's from the sweet spot of language era where it's old enough to have 
an established ecosystem and practices and great tools and it's recognized, but also young enough 
that it feels modern. I think my biggest problem with Common Lisp is that even though it's great, 
some things in it just feel old. The reader macro system, while phenomenal and incredibly powerful, 
makes for messy code. The language has a small standard library, but still feels bloated. There's 
so many different ways of doing things and a lot of code ends up just feeling very verbose.

Enter Racket. It's a derivative of Scheme, not Common Lisp, which has traditionally had it's 
emphasis on a minimalist language. Minimalism is great, Scheme doesn't feel bloated the way Common 
Lisp does, code is pretty clean, the reader macro system while equally as powerful feels less 
intrusive, and these make it feel a lot nicer to me. Racket is a derivative of Scheme, but it takes 
the minimalism and throws it out the door purely in terms of the standard library. The syntax is 
Scheme, so your core language isn't bloated with reader macro symbols all over the place like 
Common Lisp and the code is a lot less verbose, but it's powerful. The standard library contains 
libraries for building full GUIs, webservers, multithreading, cli applications, etc., it's great. 
Because it's a Lisp, it's also dynamically typed. However, Racket even includes a library for 
adding static typing to the language, so you get the best of both worlds. The reason Racket has so 
much in it's standard library is because it was built as a language for teaching. University of 
Waterloo teaches Racket as a first language for example. But since it was built with teaching in 
mind, it's got to be able to do all the things that you would normally teach someone to do in a 
language, which happens to cover a lot of use cases. Racket also defines itself as being a 
"language oriented programming"  language, which is a weird way of saying that one of the primary 
goals of the language is to facilitate making languages. So it's great for creating all sorts of 
DSLs that are built on top of Racket instead of the normal process of creating a YAML parser for 50 
different languages.

Again, being a teaching language, it itself has phenomenal documentation, but not just docs, it 
also has guides. And it has guides for every level of programmer. Never touched programming before? 
It's got official guides and textbooks for getting started. Programmed but never used Lisp? They've 
got you covered. Advanced programmer and dabbled in Lisp? Used Lisp but not convinced you should 
use it in a production system? Want to use it in a production system but don't know where to get 
started? They have it all, so many guides. And the guides are built in a wonderful way, they have a 
system that automatically links you to the docs for the name of every function, which I know is 
nothing new or revolutionary, but it's still highly appreciated to have. It makes it super easy to 
follow the guides. And when you do click on those links to check a reference, the whole language is 
really well documented, it's super easy to understand what everything does. The docs for the 
~parameterize~ function for example have 5 different examples - although that is higher than most to 
be fair.

Racket also ships with a text editor called DrRacket, which is a fantastic editor for testing the 
waters without needing to delve into Emacs, because Emacs is hard, but also the only full fledged 
environment for doing most serious Lisp programming. DrRacket has you covered through for Racket 
stuff. When you hover over a function, it'll show you where exactly that function comes from, you 
can peek definitions super easily, etc., and again, this is nothing revolutionary, but it's great 
for learning the language and seeing what package is used where and stuff. It's got a terminal 
that's able to draw in non-ascii, which is great because some of the guides allow you to just learn 
by doing fun stuff by drawing simple shapes and seeing how you can expand just drawing simple 
shapes to repeating them, making matrices out of them and expanding them into building a checkers 
board for example. It's nothing revolutionary, but it's done well, and it makes you enjoy what 
you're doing.

Finally, Racket makes things really easy. When I'm writing code, it feels like the Python of Lisp 
languages (although with better benchmarks than Python). It's super easy to use, read and learn. 
It's really powerful and it's fun to use. One of the guides that I read through was for building a 
multi-threaded webserver from scratch using just their TCP-socket stuff from their standard
library. My whole webserver was only 30 lines of code, and while all it can do right now is send 
back "Hello world", I already knew after just an hour of using the language how I could make it into
a much more full-featured web server. Except I don't have to do that, because Racket already has a 
full-featured web server that ships with it.

Racket has been a joy to learn, and I'd love to continuing to use it for my own projects. For 
anyone looking for learn a new language in their spare time, I would 10/10 recommend giving Racket 
a shot.

If you want to get started with Racket, just take a look at the guides on the offical Racket 
website, they're all phenomenal: https://docs.racket-lang.org/guide/index.htm
